spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:${MONGODB_URI:mongodb+srv://shrawanyadkr2:sky%406299@cluster0.uyjza.mongodb.net/resumebuilder?retryWrites=true&w=majority}}
spring.data.mongodb.database=resumebuilder

# Email Configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:b33bd2001@smtp-brevo.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:bsk6zz6BAUuMJQO}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${SPRING_MAIL_FROM:shrawan29yadav@gmail.com}

# Application Information
app.base.url=${APP_BASE_URL:http://localhost:8080}

# Cloudinary Information
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:zbgbxmxi}
cloudinary.api-key=${CLOUDINARY_API_KEY:644989297226411}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:ISW9Ad8JLAzTcwEqCPmxPmUBe2s}

# JWT Configuration
jwt.secret=${JWT_SECRET:your-secret-key-here-change-this-in-production-with-more-secure-and-complicated-key}
jwt.expiration=${JWT_EXPIRATION:604800000}

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_TIY8F95ZYQV2PN}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:zG91YL3lbzo3T9c3ypbeMLyk}

# Actuator Health Indicators Configuration
management.endpoints.web.exposure.include=health,info
management.health.mongo.enabled=false
management.health.mail.enabled=false
