spring.data.mongodb.uri=
spring.data.mongodb.database=

# Email Configuration
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=
spring.mail.properties.mail.smtp.ssl.enable=
spring.mail.properties.mail.smtp.ssl.trust=
spring.mail.properties.mail.smtp.socketFactory.port=
spring.mail.properties.mail.smtp.socketFactory.class=
spring.mail.properties.mail.smtp.socketFactory.fallback=
spring.mail.properties.mail.smtp.from=

# Application Information
app.client.url=
app.base.url=

# Cloudinary Information
cloudinary.cloud-name=
cloudinary.api-key=
cloudinary.api-secret=

# JWT Configuration
jwt.secret=
jwt.expiration=

# Razorpay Configuration
razorpay.key.id=
razorpay.key.secret=

# Actuator Health Indicators Configuration
management.endpoints.web.exposure.include=health,info
management.health.mongo.enabled=false
management.health.mail.enabled=false
